/*
	Copyright 2023 Efabless Corp.

	Author: Mohamed Shalan (mshalan@efabless.com)

	This file is auto-generated by wrapper_gen.py

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


#define ACMP_BASE				0x00000000

#define	ACMP_SEL_REG_ADDR		(ACMP_BASE+0x0)
#define	ACMP_ICR_REG_ADDR		(ACMP_BASE+0xf00)
#define	ACMP_RIS_REG_ADDR		(ACMP_BASE+0xf04)
#define	ACMP_IM_REG_ADDR		(ACMP_BASE+0xf08)
#define	ACMP_MIS_REG_ADDR		(ACMP_BASE+0xf0c)

#define ACMP_SEL_REG_SELA		0
#define ACMP_SEL_REG_SELA_LEN	1
#define ACMP_SEL_REG_SELB		1
#define ACMP_SEL_REG_SELB_LEN	1
#define INT_HI_FLAG	0x1

volatile unsigned int * acmp_SEL	= (volatile unsigned int *) ACMP_SEL_REG_ADDR;
